[common]
default_envs = yolo_uno

[env:yolo_uno]
platform = espressif32
board = yolo_uno
framework = arduino
monitor_speed = 115200
build_flags = 
	-D ARDUINO_USB_MODE=1
	-D ARDUINO_USB_CDC_ON_BOOT=1
	-include project_config.h
lib_deps = 
	Adafruit_NeoPixel
	LiquidCrystal_I2C
	https://github.com/me-no-dev/ESPAsyncWebServer.git
	https://github.com/RobTillaart/DHT20
	https://github.com/adafruit/Adafruit_MQTT_Library
	adafruit/Adafruit NeoPixel@^1.15.1
	esp32async/AsyncTCP@^3.4.9
	knolleary/PubSubClient@^2.8.0
	bblanchon/ArduinoJson
	tanakamasayuki/TensorFlowLite_ESP32@1.0.0

lib_extra_dirs = 
	lib
	lib/Utils
lib_ldf_mode = deep
lib_ignore = WiFi101
board_build.filesystem = spiffs
board_build.partitions = yolo_uno_8MB.csv